import type { Config } from "tailwindcss";

/*
 * Mapeo de los tokens de diseño (styles/tokens.css + styles/tokens-extendidos.css).
 * La escala por defecto de Tailwind se reemplaza para que los componentes
 * solo puedan usar valores del sistema de Marina Gold.
 */
const v = (name: string) => `var(--mg-${name})`;

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  future: {
    // Los hover solo se aplican con puntero fino: @media (hover: hover)
    hoverOnlyWhenSupported: true,
  },
  theme: {
    screens: {
      md: "768px",
      lg: "1024px",
      xl: "1440px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      mg: {
        black: v("black"),
        white: v("white"),
        red: v("red"),
        "red-hover": v("red-hover"),
        "black-hover": v("black-hover"),
        bone: v("bone"),
        ink: v("ink"),
        "ink-2": v("ink-2"),
        "ink-3": v("ink-3"),
        line: v("line"),
        border: v("border"),
        "on-dark": v("on-dark"),
        "on-dark-muted": v("on-dark-muted"),
        "on-dark-soft": v("on-dark-soft"),
        "on-dark-border": v("on-dark-border"),
        "on-dark-line": v("on-dark-line"),
        manjar: v("manjar"),
        "manjar-deep": v("manjar-deep"),
        maracuya: v("maracuya"),
        "maracuya-deep": v("maracuya-deep"),
        fresa: v("fresa"),
        "fresa-deep": v("fresa-deep"),
        "soldout-veil": v("soldout-veil"),
        overlay: v("overlay"),
        focus: v("focus"),
        placeholder: v("placeholder"),
        "placeholder-dark": v("placeholder-dark"),
        "segment-off": v("segment-off"),
        "hero-veil": v("hero-veil"),
      },
    },
    fontFamily: {
      serif: v("serif"),
      sans: v("sans"),
    },
    fontSize: {
      "mg-footer-logo": v("text-footer-logo"),
      "mg-hero": v("text-hero"),
      "mg-h1": v("text-h1"),
      "mg-h2": v("text-h2"),
      "mg-h2-lg": v("text-h2-lg"),
      "mg-h3": v("text-h3"),
      "mg-accent": v("text-accent"),
      "mg-signature": v("text-signature"),
      "mg-price-lg": v("text-price-lg"),
      "mg-occasion": v("text-occasion"),
      "mg-inside-name": v("text-inside-name"),
      "mg-card-title": v("text-card-title"),
      "mg-logo": v("text-logo"),
      "mg-body": v("text-body"),
      "mg-sticky-name": v("text-sticky-name"),
      "mg-accordion": v("text-accordion"),
      "mg-price": v("text-price"),
      "mg-faq": v("text-faq"),
      "mg-subtitle": v("text-subtitle"),
      "mg-button": v("text-button"),
      "mg-hero-eyebrow": v("text-hero-eyebrow"),
      "mg-footer-link": v("text-footer-link"),
      "mg-small": v("text-small"),
      "mg-button-sm": v("text-button-sm"),
      "mg-sticky-meta": v("text-sticky-meta"),
      "mg-tab": v("text-tab"),
      "mg-copyright": v("text-copyright"),
      "mg-eyebrow": v("text-eyebrow"),
      "mg-announce": v("text-announce"),
      "mg-badge": v("text-badge"),
    },
    lineHeight: {
      none: "1",
      logo: v("leading-logo"),
      tight: v("leading-tight"),
      heading: v("leading-heading"),
      card: v("leading-card"),
      note: v("leading-note"),
      body: v("leading-body"),
      long: v("leading-long"),
    },
    letterSpacing: {
      none: v("tracking-none"),
      h1: v("tracking-h1"),
      h3: v("tracking-h3"),
      card: v("tracking-card"),
      "hero-eyebrow": v("tracking-hero-eyebrow"),
      option: v("tracking-option"),
      logo: v("tracking-logo"),
      button: v("tracking-button"),
      label: v("tracking-label"),
      eyebrow: v("tracking-eyebrow"),
    },
    spacing: {
      0: "0",
      px: "1px",
      0.5: v("space-0-5"),
      0.75: v("space-0-75"),
      1: v("space-1"),
      1.25: v("space-1-25"),
      1.5: v("space-1-5"),
      1.75: v("space-1-75"),
      2: v("space-2"),
      2.25: v("space-2-25"),
      2.5: v("space-2-5"),
      2.75: v("space-2-75"),
      3: v("space-3"),
      3.5: v("space-3-5"),
      4: v("space-4"),
      4.5: v("space-4-5"),
      5: v("space-5"),
      6: v("space-6"),
      7: v("space-7"),
      8: v("space-8"),
      9: v("space-9"),
      10: v("space-10"),
      12: v("space-12"),
      gutter: v("gutter"),
      "section-top": v("section-top"),
      "section-bottom": v("section-bottom"),
      "grid-col": v("grid-col-gap"),
      "grid-row": v("grid-row-gap"),
      touch: v("touch"),
      "btn-lg": v("btn-lg"),
      "btn-md": v("btn-md"),
      announce: v("announce-h"),
      header: v("header-h"),
      option: v("size-option-h"),
      accordion: v("accordion-row"),
      "faq-row": v("faq-row"),
      sticky: v("sticky-bar-h"),
      "pay-w": v("pay-logo-w"),
      "pay-h": v("pay-logo-h"),
      checkbox: v("checkbox"),
      dot: v("dot"),
      counter: v("counter-h"),
      "cart-count": v("cart-count"),
      "hero-btn-min": v("hero-btn-min"),
      "qty-cell": v("qty-cell"),
      "qty-value": v("qty-value"),
      "inside-photo": v("inside-photo"),
      occasion: v("occasion-card"),
      "thumb-w": v("thumb-w"),
      "thumb-h": v("thumb-h"),
      drawer: v("drawer-w"),
      "icon-xs": v("icon-xs"),
      "icon-bell": v("icon-bell"),
      "icon-sm": v("icon-sm"),
      "icon-md": v("icon-md"),
      "icon-header": v("icon-header"),
      "icon-lg": v("icon-lg"),
      "icon-xl": v("icon-xl"),
      "social-icon": v("social-icon"),
    },
    borderRadius: {
      none: v("radius"),
      pay: v("radius-pay"),
      pill: v("radius-pill"),
    },
    borderWidth: {
      0: "0",
      DEFAULT: v("border-w"),
      2: v("border-w-selected"),
      hero: v("border-w-hero"),
    },
    boxShadow: {
      none: "none",
      sticky: v("shadow-sticky"),
      drawer: v("shadow-drawer"),
    },
    aspectRatio: {
      hero: v("ratio-hero"),
      box: v("ratio-box"),
      flavor: v("ratio-flavor"),
      "hero-desktop": "16 / 9",
    },
    maxWidth: {
      none: "none",
      container: v("container"),
      product: v("container-product"),
      faq: v("faq-max"),
    },
    transitionDuration: {
      0: "0ms",
      fast: v("dur-fast"),
      base: v("dur-base"),
      slow: v("dur-slow"),
      reveal: v("dur-reveal"),
    },
    transitionTimingFunction: {
      mg: v("ease"),
      linear: "linear",
    },
    extend: {
      backgroundImage: {
        surtida: v("surtida"),
      },
      outlineOffset: {
        focus: v("space-0-5"),
      },
    },
  },
  plugins: [],
};

export default config;
